### ISSUE TITLE
https://github.com/CocoaPods/CLAide.git (at master@a5d1a29) is not yet checked out.

### ISSUE THREAD

**Issue by jakub-trzebiatowski** [ronnnnn/asdf-cocoapods#3]
**Describe the bug**

After installing `asdf`, installing `asdf-cocoapods`, when I attempt to run `pod --version`, I get...

```
https://github.com/CocoaPods/CLAide.git (at master@a5d1a29) is not yet checked out. Run `bundle install` first.
```

I'm not running this in any particular directory, I'd like to get the `pod` command to run at all. Of course `bundle install` doesn't work, complaining about missing `Gemfile`.

I use Ruby `2.7.5` via `rbenv`.

**Expected behavior**

`pod --version` should print the used CocoaPods version.

**Comment by ronnnnn** [comment]
@cubuspl42 
Thank you for reporting issue.

asdf-cocoapods downloads CocoaPods's binary and install it via Bundler.
https://github.com/ronnnnn/asdf-cocoapods/blob/8c52ec16f3780feda37be20285858d887024e84f/lib/utils.bash#L62

If you execute pod command before install the binary via Bundler, the error will happen.
Therefore, I can't figure out why the error occurred currently.

Tell me Bundler version and your OS info, too.

**Comment by ronnnnn** [comment]
@cubuspl42 
I faced same error on my another laptop.
This is a log when I installed. I used Ruby and RubyGems that are installed default.

```
❯ asdf install cocoapods latest      
redirect url: https://github.com/CocoaPods/CocoaPods/releases/tag/1.12.1
install version is 1.12.1
* Downloading cocoapods release 1.12.1...
cp: /Users/seiyakokushi/.asdf/downloads/cocoapods/1.12.1/examples/OnDemandResources Example/TestLibrary/_Pods.xcodeproj: No such file or directory
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin22/rbconfig.rb:21: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
Your RubyGems version (3.0.3.1) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`
Fetching gem metadata from https://rubygems.org/...........
Fetching https://github.com/CocoaPods/CLAide.git
There was an error while trying to write to `/Library/Ruby/Gems/2.6.0/cache/bundler/git`. It is likely
that you need to grant write permissions for that path.
cocoapods 1.12.1 installation was successful!
```

After I installed latest Ruby with `asdf-ruby` and reinstalled CocoaPods with `asdf-cocoapods`, the error doesn't appear.
So, I recommend that you should use latest Ruby version with `asdf-ruby`.

**Comment by vshkl** [comment]
In case someone end up here struggling to make it work with the latest ASDF – 0.18.0 in my case – keep in mind that `asdf global` is no longer a thing: https://asdf-vm.com/guide/upgrading-to-v0-16.html#asdf-global-and-asdf-local-commands-have-been-replaced-with-asdf-set.  So the resolution from the README still holds, except that instead from `asdf global` you'll have to do `asdf set` in `cd ~/.asdf/installs/cocoapods/{version}`.

**Comment by bonesyblue** [comment]
Thanks for the hint @vshkl - that really helped me out! For anybody who arrives here also running into this issue - here are the steps I took to install cocoapods 1.16.2:

```bash
# Install ruby
asdf plugin add ruby
asdf install ruby 3.2.9

# Set the "global" ruby version to 3.2.9
asdf set -u ruby 3.2.9

# Verify the Ruby version
ruby --version

# Install Cocoapods
asdf plugin add cocoapods
asdf install cocoapods 1.16.2
asdf set cocoapods 1.16.2

# Verify the CocoaPods version
pod --version
```
