### ISSUE TITLE
asdf pod not updated with cocoapods

### ISSUE THREAD

**Issue by Shahrukh0396** [ronnnnn/asdf-cocoapods#7]
**Describe the bug

i was trying to update cocoapods using asdf and it was updated successfully to latest version 1.15.2 but pod --version still shows me 1.11.3. 

**Steps to reproduce**

pod --version
1.11.3

whereis pod          
pod: /Users/shahrukh/.asdf/shims/pod

which pod            
/Users/shahrukh/.asdf/shims/pod

asdf current cocoapods
cocoapods       1.15.2          /Users/shahrukh/.tool-versions

**Expected behavior**

pod --version should return the same version as cocoapods

Please help!

**Comment by ronnnnn** [comment]
@Shahrukh0396 
Have you already tried the `asdf reshim` command? [^1]

If it still doesn't work, please try reinstalling the plugin in the following order after removing it.

```sh
asdf plugin-remove ruby
asdf plugin-remove bundler
asdf plugin-remove cocoapods
asdf plugin-add ruby
asdf plugin-add bundler
asdf plugin-add cocoapods
asdf install ruby <version>
asdf install bundler <version>
asdf install cocoapods <version>
```

The .tool-versions file doesn't care about the installation order, so it's important to manually install them in sequence.

[^1]: https://asdf-vm.com/manage/core.html#reshim

**Comment by Shahrukh0396** [comment]
thanks @ronnnnn this really worked like a charm.
